name: Deploy to EC2
  
on:
    # push:
    #   branches:
    #     - main
    workflow_dispatch:
  
jobs:
    Deployment_on_EC2:
      runs-on: ubuntu-latest
    
      steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
    
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
  
        
      - name: Deploy Docker Compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.7.58.56 << EOF
            set -e
            cd /home/ubuntu/secTheta
            git pull https://github.com/kaur-rajdeep/lms.git
            npm install
            npm run build
            sudo systemctl reload nginx 
          EOF
    
